[program:app]
command=uv run flask run --host=0.0.0.0 --port=8050
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=FLASK_APP="app.py"
